[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
on_event = ['InsertEnter', 'CmdlineEnter']
lua_source = '''
    vim.cmd.source('~/dotfiles/.vim/settings/ddc_rc.vim')
    require('ddc_rc')
'''

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = ['ddc.vim']

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = ['ddc.vim']

# source
[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = ['ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-cmdline_history'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = ['ddc.vim']
lua_post_source = '''
    vim.cmd.source('~/dotfiles/.vim/lua/nvim-lsp.lua')
'''

[[plugins]]
repo = 'Shougo/ddc-source-input'
on_source = ['ddc.vim']

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = ['ddc.vim']

[[plugins]]
repo = 'tani/ddc-path'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-shell_native'
on_source = ['ddc.vim']

[[plugins]]
repo = 'delphinus/ddc-shell-history'
on_source = ['ddc.vim']

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'
on_source = ['ddc.vim']

